# Import Libraries

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
# display all columns of the dataframe
pd.options.display.max_columns = None

# Load Dataset - after part 1

In [2]:
df=pd.read_csv(r'C:\Users\SACHIN\Desktop\CAPSTONE PROJECT\Official Capstone diabetes Project\Data set CSV\dataset_diabetes UCI\Diabetes_preprocessing_1.csv')
df.head()

gender  age admission_type_id discharge_disposition_id admission_source_id  \
0       0   15         Emergency       Discharged to home           Emergency   
1       0   25         Emergency       Discharged to home           Emergency   
2       1   35         Emergency       Discharged to home           Emergency   
3       1   45         Emergency       Discharged to home           Emergency   
4       1   55         Emergency       Discharged to home            Referral   

   time_in_hospital  num_lab_procedures  num_procedures  num_medications  \
0                 3                  59               0               18   
1                 2                  11               5               13   
2                 2                  44               1               16   
3                 1                  51               0                8   
4                 3                  31               6               16   

  diag_1  diag_2 diag_3  number_diagnoses  max_glu_serum  A1Cresult  \
0    276  250.01    255                 9              0          0   
1    648     250    V27                 6              0          0   
2      8  250.43    403                 7              0          0   
3    197     157    250                 5              0          0   
4    414     411    250                 9              0          0   

   metformin  glipizide  glyburide  insulin  change  diabetesMed  readmitted  \
0          0          0          0        1       1            1           0   
1          0          0          0        0       0            1           0   
2          0          0          0        1       1            1           0   
3          0          0          0        0       1            1           0   
4          0          0          0        0       0            1           0   

   service_utilization  Asian  Caucasian  Hispanic  Other  
0                    0      0          1         0      0  
1                    3      0          0         0      0  
2                    0      0          1         0      0  
3                    0      0          1         0      0  
4                    0      0          1         0      0

In [3]:
df.shape

(97805, 27)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97805 entries, 0 to 97804
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   gender                    97805 non-null  int64 
 1   age                       97805 non-null  int64 
 2   admission_type_id         97805 non-null  object
 3   discharge_disposition_id  97805 non-null  object
 4   admission_source_id       97805 non-null  object
 5   time_in_hospital          97805 non-null  int64 
 6   num_lab_procedures        97805 non-null  int64 
 7   num_procedures            97805 non-null  int64 
 8   num_medications           97805 non-null  int64 
 9   diag_1                    97805 non-null  object
 10  diag_2                    97805 non-null  object
 11  diag_3                    97805 non-null  object
 12  number_diagnoses          97805 non-null  int64 
 13  max_glu_serum             97805 non-null  int64 
 14  A1Cresult             

# Encoding


1. admission_type_id :

In [5]:
df['admission_type_id'].value_counts()

Emergency        69486
Elective         18344
Not Available     9975
Name: admission_type_id, dtype: int64

In [6]:
df['admission_type_id'].unique()

array(['Emergency', 'Elective', 'Not Available'], dtype=object)

In [7]:
df['admission_type_id']=df['admission_type_id'].replace({'Emergency':0,'Elective':1,'Not Available':2})

2. discharge_disposition_id

In [8]:
df['discharge_disposition_id'].value_counts()

Discharged to home                            71928
Transferred to another facility               20574
Not Available                                  4598
Left AMA                                        604
Still patient/referred to this institution      101
Name: discharge_disposition_id, dtype: int64

In [9]:
df['discharge_disposition_id'].unique()

array(['Discharged to home', 'Transferred to another facility',
       'Left AMA', 'Not Available',
       'Still patient/referred to this institution'], dtype=object)

In [10]:
df['discharge_disposition_id']=df['discharge_disposition_id'].replace({'Discharged to home':0,'Transferred to another facility':1,
                                                                       'Not Available':2,'Left AMA':3,
                                                                       'Still patient/referred to this institution':4})

In [11]:
df['discharge_disposition_id'].value_counts()

0    71928
1    20574
2     4598
3      604
4      101
Name: discharge_disposition_id, dtype: int64

3. admission_source_id

In [12]:
df['admission_source_id'].value_counts()

Emergency                    55166
Referral                     29881
Not Available                 6743
Transferred from hospital     6015
Name: admission_source_id, dtype: int64

In [13]:
df['admission_source_id']=df['admission_source_id'].replace({'Emergency':0,'Referral':1,
                                                             'Not Available':2,'Transferred from hospital':3})

In [14]:
df['admission_source_id'].value_counts()

0    55166
1    29881
2     6743
3     6015
Name: admission_source_id, dtype: int64

In [15]:
df.head()

gender  age  admission_type_id  discharge_disposition_id  \
0       0   15                  0                         0   
1       0   25                  0                         0   
2       1   35                  0                         0   
3       1   45                  0                         0   
4       1   55                  0                         0   

   admission_source_id  time_in_hospital  num_lab_procedures  num_procedures  \
0                    0                 3                  59               0   
1                    0                 2                  11               5   
2                    0                 2                  44               1   
3                    0                 1                  51               0   
4                    1                 3                  31               6   

   num_medications diag_1  diag_2 diag_3  number_diagnoses  max_glu_serum  \
0               18    276  250.01    255                 9              0   
1               13    648     250    V27                 6              0   
2               16      8  250.43    403                 7              0   
3                8    197     157    250                 5              0   
4               16    414     411    250                 9              0   

   A1Cresult  metformin  glipizide  glyburide  insulin  change  diabetesMed  \
0          0          0          0          0        1       1            1   
1          0          0          0          0        0       0            1   
2          0          0          0          0        1       1            1   
3          0          0          0          0        0       1            1   
4          0          0          0          0        0       0            1   

   readmitted  service_utilization  Asian  Caucasian  Hispanic  Other  
0           0                    0      0          1         0      0  
1           0                    3      0          0         0      0  
2           0                    0      0          1         0      0  
3           0                    0      0          1         0      0  
4           0                    0      0          1         0      0

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97805 entries, 0 to 97804
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   gender                    97805 non-null  int64 
 1   age                       97805 non-null  int64 
 2   admission_type_id         97805 non-null  int64 
 3   discharge_disposition_id  97805 non-null  int64 
 4   admission_source_id       97805 non-null  int64 
 5   time_in_hospital          97805 non-null  int64 
 6   num_lab_procedures        97805 non-null  int64 
 7   num_procedures            97805 non-null  int64 
 8   num_medications           97805 non-null  int64 
 9   diag_1                    97805 non-null  object
 10  diag_2                    97805 non-null  object
 11  diag_3                    97805 non-null  object
 12  number_diagnoses          97805 non-null  int64 
 13  max_glu_serum             97805 non-null  int64 
 14  A1Cresult             

4. diag_1,diag_2,diag_3

- Diagnosis 1 (Nominal) : The primary diagnosis (coded as first three digits of ICD9); 848 distinct values
- Diagnosis 2 (Nominal) : Secondary diagnosis (coded as first three digits of ICD9); 923 distinct values
- Diagnosis 3 (Nominal) : Additional secondary diagnosis (coded as first three digits of ICD9); 954 distinct values 

- Diabetes:0
- Circulatory:1
- Respiratory:2
- Digestive:3
- Injury:4
- Musculoskelet:5
- Genitourinory:6
- Neoplasms:7
- Others:8

In [17]:
df.loc[df['diag_1'].str.contains('V',na=False),['diag_1']]=8 #Others
df.loc[df['diag_1'].str.contains('E',na=False),['diag_1']]=8
df.loc[df['diag_2'].str.contains('V',na=False),['diag_2']]=8
df.loc[df['diag_2'].str.contains('E',na=False),['diag_2']]=8
df.loc[df['diag_3'].str.contains('V',na=False),['diag_3']]=8
df.loc[df['diag_3'].str.contains('E',na=False),['diag_3']]=8

In [18]:
df['diag_1']=df['diag_1'].astype('float')
df['diag_2']=df['diag_2'].astype('float')
df['diag_3']=df['diag_3'].astype('float')

- Diagnosis” stands for a primary diagnosis with possible values: 
- “circulatory” for icd9: 390–459, 785, 
- “digestive”—icd9: 520–579, 787; 
- “genitourinary”—icd9:580–629, 788, 
- “diabetes”—icd9: 250.xx, 
- “injury” icd9: 800–999, 
- “musculoskeletal”—icd9: 710–739; 
- “neoplasms”—icd9: 140–239,
- “respiratory” icd9: 460–519,786, 
- “other” otherwise.

In [19]:
for j in ['diag_1','diag_2','diag_3']:
    for i in range(0,len(df)):
        if (np.floor(df.loc[i,j]) == 250):
            df.loc[i, j] = 0 #Diabetes
        elif (df.loc[i, j] >= 390 and df.loc[i, j] < 460) or (np.floor(df.loc[i,j]) == 785):
            df.loc[i, j] = 1 #Circulatory
        elif (df.loc[i, j] >= 460 and df.loc[i, j] < 520) or (np.floor(df.loc[i,j]) == 786):
            df.loc[i, j] = 2 #Respiratory
        elif (df.loc[i, j] >= 520 and df.loc[i, j] < 580) or (np.floor(df.loc[i,j]) == 787):
            df.loc[i, j] = 3 #Digestive
        elif (df.loc[i, j] >= 800 and df.loc[i, j] < 1000):
            df.loc[i, j] = 4 #Injury
        elif (df.loc[i, j] >= 710 and df.loc[i, j] < 740):
            df.loc[i, j] = 5 #Musculoskelet
        elif (df.loc[i, j] >= 580 and df.loc[i, j] < 630) or (np.floor(df.loc[i,j]) == 788):
            df.loc[i, j] = 6 #Genitourinory
        elif (df.loc[i, j] >= 140 and df.loc[i, j] < 240):
            df.loc[i, j] = 7 #Neoplasms
        else:
            df.loc[i, j] = 8 #Others

In [20]:
for i in ['diag_1','diag_2','diag_3']:
    print(df[i].unique())

[8. 7. 1. 0. 2. 4. 5. 3. 6.]
[0. 7. 1. 2. 8. 4. 5. 6. 3.]
[8. 1. 0. 2. 4. 7. 6. 5. 3.]


In [21]:
df['diag_1']=df['diag_1'].astype('int')
df['diag_2']=df['diag_2'].astype('int')
df['diag_3']=df['diag_3'].astype('int')

In [22]:
df.head()

gender  age  admission_type_id  discharge_disposition_id  \
0       0   15                  0                         0   
1       0   25                  0                         0   
2       1   35                  0                         0   
3       1   45                  0                         0   
4       1   55                  0                         0   

   admission_source_id  time_in_hospital  num_lab_procedures  num_procedures  \
0                    0                 3                  59               0   
1                    0                 2                  11               5   
2                    0                 2                  44               1   
3                    0                 1                  51               0   
4                    1                 3                  31               6   

   num_medications  diag_1  diag_2  diag_3  number_diagnoses  max_glu_serum  \
0               18       8       0       8                 9              0   
1               13       8       0       8                 6              0   
2               16       8       0       1                 7              0   
3                8       7       7       0                 5              0   
4               16       1       1       0                 9              0   

   A1Cresult  metformin  glipizide  glyburide  insulin  change  diabetesMed  \
0          0          0          0          0        1       1            1   
1          0          0          0          0        0       0            1   
2          0          0          0          0        1       1            1   
3          0          0          0          0        0       1            1   
4          0          0          0          0        0       0            1   

   readmitted  service_utilization  Asian  Caucasian  Hispanic  Other  
0           0                    0      0          1         0      0  
1           0                    3      0          0         0      0  
2           0                    0      0          1         0      0  
3           0                    0      0          1         0      0  
4           0                    0      0          1         0      0

# Export CSV - cleaned dataset part 2

In [23]:
#df.to_csv('Diabetes_preprocessing_2.csv', index = False)

# END